name: Generar APK Automatizador
on: [push]

jobs:
  compilar:
    runs-on: ubuntu-22.04
    steps:
      - name: Obtener archivos
        uses: actions/checkout@v4

      - name: Instalar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar herramientas necesarias
        run: |
          sudo apt update -y
          sudo apt install -y openjdk-17-jdk build-essential git libffi-dev libssl-dev
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.37

      - name: Generar el APK
        run: buildozer android debug --allow-root

      - name: Dejar APK listo para descargar
        uses: actions/upload-artifact@v4
        with:
          name: APK_Automatizador_Reclamos
          path: bin/*.apk
